module.exports.default = {
    DISCONNECT: 'DISCONNECT',
    JOIN_ROOM: 'JOIN_ROOM',
    USERS_MODIFIED: 'USERS_MODIFIED',
    GET_CONNECTION_ID: 'GET_CONNECTION_ID',
    ADD_SCORE: 'ADD_SCORE',
    USER_VOTED: 'USER_VOTED',
    SET_AVG: 'SET_AVG',
    GET_AVG: 'GET_AVG'
};
